services:
  db:
    image: postgres:18
    container_name: burunzhuy_db
    ports:
      - "5433:5432"
#      - "5433:5432"
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
#    volumes:
#      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.12
    container_name: burunzhuy_pgadmin
    ports:
      - "5434:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD}'
      PMA_HOST: db
    depends_on:
      - db


volumes:
  pgdata: