spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/burunzhuy
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jwt:
    secret: ${env.JWT_SECRET}
    lifetime_token: 3600000
    lifetime_refresh_token: 604800000

storage:
  upload-dir: uploads/

resend:
  email-from: "onboarding@resend.dev"
  api-key: "re_2***"